# Generated by Django 4.1.2 on 2022-10-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('FINISHED', 'FINISHED')], max_length=45)),
                ('category', models.CharField(choices=[('IMPORTANT', 'IMPORTANT'), ('URGENT', 'URGENT'), ('NORMAL', 'NORMAL')], default='', max_length=45)),
                ('priority', models.CharField(choices=[('PRIORITY', 'PRIORITY'), ('NON-PRIORITY', 'NON-PRIORITY')], default='', max_length=45)),
                ('task_image', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
